### ISSUE TITLE
Will you keep the reversed proxy server closed (with restricted Access-Control-Allow-Origin)

### ISSUE THREAD

**Issue by Animenosekai** [WolfreeAlpha/WolfreeAlpha.github.io#16]
Hi,
I forked your project to make one with a design really close to the real WolframAlpha one.

I'm using it with my classmates and I just discovered that you have restricted access to your CORS reverse proxy server (lin2jing4-cors.herokuapp.com) so I would like to know if this was temporary.

(btw, my project is not indexed by Google because I only wanted to share it with my friends) (you can see that it is not Indexed in index.html --> `<meta name="robots" content="noindex">`)

Here is the project: https://github.com/Animenosekai/freeWolframAlpha
Here is a link to the project online (the queries won't work because they aren't allowed by CORS): https://freewolframalpha.netlify.app

**Comment by Lin2Jing4** [comment]
lin2jing4-cors.herokuapp.com stopped serving as a public proxy by January 1st, 2021. This is *not* temporary. I opened a [pull request](https://github.com/Animenosekai/freeWolframAlpha/pull/1) 16 days ago (2020-12-17T03:06:27Z). You should self-host [CORS Anywhere](https://github.com/Rob--W/cors-anywhere#demo-server). Let me know if you need further help.

**Comment by Animenosekai** [comment]
> lin2jing4-cors.herokuapp.com stopped serving as a public proxy by January 1st, 2021. This is _not_ temporary. I opened a [pull request](https://github.com/Animenosekai/freeWolframAlpha/pull/1) 16 days ago (2020-12-17T03:06:27Z). You should self-host [CORS Anywhere](https://github.com/Rob--W/cors-anywhere#demo-server). Let me know if you need further help.

Ok ok (don't worry I know how to use CORS Anywhere but I think that I'll use my own built reverse proxy in Python because as you might know the Heroku Free plan is limited in terms of monthly usage and I already have servers running on Flask/Python)

**Comment by Animenosekai** [comment]
If someone wants to know, it's very simple to make a proxy for WolframAlpha, just make a Flask endpoint which makes the request for you.

Here is an example snippet of code which comes from my server script:
```python
from flask import request, Response
from requests import get

@ErinaServer.route("/freeWolframAlpha/api/query")
def freeWolframAlpha_query():
    response = get(f"https://api.wolframalpha.com/v2/query?appid={str(request.values.get('appID', None))}&input={str(request.values.get('question', None)).replace('+', '%2b')}&podstate=Step-by-step+solution&podstate=Step-by-step&podstate=Show+all+steps&scantimeout=20")
    newQueryResponse = Response(response.text)
    newQueryResponse.status_code = response.status_code
    return newQueryResponse
```

You now just need to make request to your server with the `appID` and the `question`
