### ISSUE TITLE
Your API keys are public

### ISSUE THREAD

**Issue by abrahammurciano** [WolfreeAlpha/WolfreeAlpha.github.io#33]

**Comment by Lin2Jing4** [comment]
There are currently two branches maintained actively in the Wolfree community:
1. [the branch maintained by Lin2Jing4](https://wolfreealpha.github.io/) and
2. [the branch maintained by Animenosekai](https://freewolframalpha.netlify.app/).

**Comment by Lin2Jing4** [comment]
The branch maintained by Lin2Jing4 only requires the server to serve as a CORS proxy.
This architecture significantly reduces the server specification requirements, but the disadvantage is that all API keys are exposed to the front-end.
If you wish to set up your own instance and keep the API keys private, please use the branch maintained by Animenosekai.

**Comment by Lin2Jing4** [comment]
Soon, after Animenosekai merges the ticket https://github.com/Animenosekai/freeWolframAlpha/pull/2, all the features available in Lin2Jing4's will be implemented and available in Animenosekai's. So the branch maintained by Animenosekai should be more suitable for your needs by then.
