### ISSUE TITLE
Can I have a choice between new design and old design?

### ISSUE THREAD

**Issue by awidesky** [WolfreeAlpha/WolfreeAlpha.github.io#37]
New designed site looks great.
But only one thing I miss is that now the result is always provided as image (at least in IOS mobile, I tested).
Older site design(or layout? I'm not sure what kind of keyword to use) printed the results in text too, but since not it's all image, I can't reuse some of my calculation results.
(e.g. in [here](https://wolfreealpha.github.io/#solve%20abs%281%2Fsqrt%282%2d2t%29%20%2d%201%29%20%3D%20abs%28%281%2Bt%29%2Fsqrt%282%29%20%2d%201%29) I want to reuse the third value of `t`, but it became really hard)

Can we have a way to get a text-formed result like days before?

**Comment by awidesky** [comment]
Hold up.
It sometimes get text form of the result just the same way in wolfram alpha.
But sometimes it show like:
![image](https://user-images.githubusercontent.com/40064726/124935031-3b28f200-e040-11eb-9b7b-8e69f00fc71c.png)
(Zoomed out a bit)
Is this problem of GUI?

**Comment by Lin2Jing4** [comment]
> Can we have a way to get a text-formed result like days before?

I'll get to work on that. For now, please use the deployment preview instead.
https://deploy-preview-29--wolfreealpha.netlify.app/
