### ISSUE TITLE
Vercel Mirrors down

### ISSUE THREAD

**Issue by Jev1337** [WolfreeAlpha/WolfreeAlpha.github.io#50]
http://wolfreealpha.vercel.app/
https://wolfree.vercel.app/

**Comment by Lin2Jing4** [comment]
Vercel blocked my user account. I cannot log in to Vercel. Try other mirror sites.

![](https://user-images.githubusercontent.com/35728132/162438944-a9341d6c-071f-4a8d-977a-8f628ca19e24.jpeg)

**Comment by Lin2Jing4** [comment]
Watch for a follow-up message in the following Gitea instances if GitHub blocks this user account.
Upstream URL: http://git.kiwifarms.net/wolfree
V3 onion service: http://it7otdanqu7ktntxzm427cba6i53w6wlanlh23v5i3siqmos47pzhvyd.onion/wolfree

**Comment by Jev1337** [comment]
> Vercel blocked my user account. I cannot log in to Vercel. Try other mirror sites.
> 
> ![](https://user-images.githubusercontent.com/35728132/162438944-a9341d6c-071f-4a8d-977a-8f628ca19e24.jpeg)

Thanks for trying to keep the project up, All I wanted to say here is to remove the broken mirror link from the main git as it does not work and be aware that they might take down more of the mirrors!

**Comment by Lin2Jing4** [comment]
Lawyers should understand how the Internet works.
Wolfram can certainly take down some mirrors, and I can always set up more mirrors.
The DMCA is just a waste of everyone's time.

**Comment by Lin2Jing4** [comment]
Lawyers should understand how the Internet works.
Wolfram can certainly take down some mirrors, and I can always set up more mirrors.
The DMCA is just a waste of everyone's time, especially in the Fediverse.

**Comment by Lin2Jing4** [comment]
Special thanks to Kiwifarms for hosting the upstream codebase.
git.kiwifarms.net and kiwifarms.cc excel at serving controversial content and have substantial experience coping with the DMCA.
